Repository thrust/cub, pull requests merged in 2020-09, with the labels that each got.

#55 Check for macro collisions with system headers during header testing.
  cmake/CubHeaderTesting.cmake
  cmake/header_test.in
Labels: multiconfig: passed, testing: passed

#54 Fixed copy-paste error in documentation
  cub/device/device_partition.cuh
Labels: documentation

#56 Add a #pragma unroll to block_radix_rank.
  cub/block/block_radix_rank.cuh
Labels: testing: passed
